In [ ]:
%%capture
import torch
major_version, minor_version = torch.cuda.get_device_capability()
# Must install separately since Colab has torch 2.2.1/2.3.0+
if major_version >= 8:
    # Use this for new GPUs like Ampere, Hopper (A100, H100, L4)
    !pip install --no-deps "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
else:
    # Use this for older GPUs like Tesla T4, V100
    !pip install --no-deps "unsloth[colab] @ git+https://github.com/unslothai/unsloth.git"

!pip install --no-deps xformers "trl<0.9.0" peft accelerate bitsandbytes

In [ ]:
%%capture
import torch
major_version, minor_version = torch.cuda.get_device_capability()

# 1. Install the Zoo first
!pip install --upgrade unsloth_zoo

# 2. Install Unsloth based on your GPU
if major_version >= 8:
    !pip install --no-deps "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
else:
    !pip install --no-deps "unsloth[colab] @ git+https://github.com/unslothai/unsloth.git"

# 3. Ensure all other critical components are present
!pip install --upgrade xformers trl peft accelerate bitsandbytes

In [ ]:
%%capture
# 1. Uninstall existing versions to avoid metadata conflicts
!pip uninstall unsloth unsloth_zoo -y

# 2. Reinstall both directly from GitHub (source) to ensure synchronization
!pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git
!pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth-zoo.git

# 3. Ensure core dependencies are updated to support the 2026 patches
!pip install --upgrade bitsandbytes accelerate xformers trl peft

In [ ]:
from unsloth import FastLanguageModel

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import torch
import json

from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments, EarlyStoppingCallback

In [ ]:
import pandas as pd

In [ ]:
training_set = pd.read_excel("/content/drive/MyDrive/Validation_AI_POC/fine_Tune_Data.xlsx")

In [ ]:
validation_set = pd.read_excel("/content/drive/MyDrive/Validation_AI_POC/val.xlsx")

In [ ]:
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

In [ ]:

def prompt_formatter(example, prompt_template):
    instruction="""You are a QA Engineer. Your task is to develop test cases based on the given requirements.
NO PROSE: Do not provide explanations, assumptions, or "Additional Information" sections.
STRICT CONSTRAINTS: 1.For every signal listed under "Signals under test", you must generate at least one dedicated test case.
Example: If there are 3 signals under test, you must generate at least 3 test cases (TC_1, TC_2, TC_3) to ensure full coverage.
2. To generate the test cases you can only use:
  - signals under test (Example: i_can_DriveModeSelector)
  - Involved input signals (Example: i_can_DriveModeSelector)
  - The following keywords: "IF", "AND", "OR", "THEN"
  - The following operators: "==", "!=", "<", ">", "<=", ">="""

    requirement=example["reqs"]
    tc=example["tc"]

    formatted_prompt = tokenizer.bos_token + prompt_template.format(instruction, requirement, tc) + tokenizer.eos_token

    return {'text': formatted_prompt}

In [ ]:
from datasets import Dataset

In [ ]:
hf_train = Dataset.from_pandas(training_set)
hf_val = Dataset.from_pandas(validation_set)

In [ ]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/mistral-7b-instruct-v0.2-bnb-4bit",
    max_seq_length=4096,
    dtype=None,
    load_in_4bit=True
)

==((====))==  Unsloth 2026.5.2: Fast Mistral patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/4.13G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/155 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/438 [00:00<?, ?B/s]

In [ ]:
tokenizer.add_bos_token, tokenizer.add_eos_token

(False, False)

In [ ]:
formatted_validation_dataset = hf_val.map(
    prompt_formatter,
    fn_kwargs={'prompt_template': alpaca_prompt}
)

Map:   0%|          | 0/9 [00:00<?, ? examples/s]

In [ ]:
formatted_training_dataset = hf_train.map(
    prompt_formatter,
    fn_kwargs={'prompt_template': alpaca_prompt}
)

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r=8,
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
    use_gradient_checkpointing=True,
    random_state=42,
    loftq_config=None
)

Unsloth 2026.5.2 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

In [ ]:
from trl import SFTTrainer, SFTConfig # Add SFTConfig here
from transformers import TrainingArguments, EarlyStoppingCallback

In [ ]:
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = formatted_training_dataset,
    eval_dataset = formatted_validation_dataset,
    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)],
    args = SFTConfig(
        max_seq_length = 4096,
        dataset_num_proc = 2,
        dataset_text_field = "text",
        packing = True,  # <--- Change this to True

        per_device_train_batch_size = 2,
        per_device_eval_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        num_train_epochs = 20,
        eval_strategy = "epoch",
        save_strategy = 'epoch',
        metric_for_best_model = "eval_loss",
        load_best_model_at_end = True,
        greater_is_better = False,
        learning_rate = 5e-5,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "paged_adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 42,
        output_dir = "outputs",
        report_to = "none",
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/64 [00:00<?, ? examples/s]

Unsloth: Packing train dataset (num_proc=2):   0%|          | 0/64 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/9 [00:00<?, ? examples/s]

Unsloth: Packing eval dataset (num_proc=2):   0%|          | 0/9 [00:00<?, ? examples/s]

🦥 Unsloth: Packing enabled - training is >2x faster and uses less VRAM!

In [ ]:
training_history = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 14 | Num Epochs = 20 | Total steps = 40
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 20,971,520 of 7,262,703,616 (0.29% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-2/tokenizer_config.json.

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-2.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-4/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-4.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-6/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-6.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-8/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-8.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-10/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-10.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-12/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-12.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-14/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-14.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-16/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-16.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-18/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-18.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-20/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-20.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-22/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-22.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-24/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-24.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-26/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-26.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-28/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-28.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-30/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-30.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-32/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-32.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-34/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-34.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-36/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-36.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-38/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-38.
Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-40/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in outputs/checkpoint-40.

In [ ]:
# @title Setup to enable bash commands
import locale

def getpreferredencoding():
    return "UTF-8"

locale.getpreferredencoding = getpreferredencoding

In [ ]:
lora_model_name = "/content/drive/MyDrive/Validation_AI_POC/Mistral_TC_gen_2"

In [ ]:
model.save_pretrained(lora_model_name)

In [ ]:
tokenizer.save_pretrained("/content/drive/MyDrive/Validation_AI_POC/Mistral_Adapters_Only")

Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/Validation_AI_POC/Mistral_Adapters_Only/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/drive/MyDrive/Validation_AI_POC/Mistral_Adapters_Only.

('/content/drive/MyDrive/Validation_AI_POC/Mistral_Adapters_Only/tokenizer_config.json',
 '/content/drive/MyDrive/Validation_AI_POC/Mistral_Adapters_Only/chat_template.jinja',
 '/content/drive/MyDrive/Validation_AI_POC/Mistral_Adapters_Only/tokenizer.json')

In [ ]:
!ls -lh {lora_model_name}

total 81M
-rw------- 1 root root 1.3K May 11 08:33 adapter_config.json
-rw------- 1 root root  81M May 11 08:33 adapter_model.safetensors
-rw------- 1 root root 5.2K May 11 08:33 README.md

In [ ]:
FastLanguageModel.for_inference(model)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): MistralForCausalLM(
      (model): MistralModel(
        (embed_tokens): Embedding(32000, 4096, padding_idx=0)
        (layers): ModuleList(
          (0-31): 32 x MistralDecoderLayer(
            (self_attn): MistralAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): MistralMLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=14336, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=14336, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): MistralRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): MistralRMSNorm((4096,), eps=1e-05)
          )
        )
        (norm): MistralRMSNorm((4096,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
    )
  )
)

In [ ]:
instruction = """You are a QA Engineer. Your task is to develop test cases based on the given requirements.
NO PROSE: Do not provide explanations, assumptions, or "Additional Information" sections.
STRICT CONSTRAINTS: 1.For every signal listed under "Signals under test", you must generate at least one dedicated test case.
Example: If there are 3 signals under test, you must generate at least 3 test cases (TC_1, TC_2, TC_3) to ensure full coverage.
2. To generate the test cases you can only use:
  - signals under test (Example: i_can_DriveModeSelector)
  - Involved input signals (Example: i_can_DriveModeSelector)
  - Involved input parameters (Example: p_tng_lka_min_speed_activation)
  - The following keywords: "IF", "AND", "OR", "THEN"
  - The following operators: "==", "!=", "<", ">", "<=", ">="""

In [ ]:
test_REQ = """"6.3.2-2 For ACC Feature :

WHEN
o_can_adas_longi_state_comfort is set to  ""2"":""ALSCT_NOREQUEST_STANDBY""
AND
i_can_VehicleSpeed is between p_tng_kph_accoff_to_acc_speed_th_low  and p_tng_kph_acc_to_accoff_speed_thd_high

IF
(i_can_SetPlusSwitche = SET/+
OR
i_can_SetMinusSwitche = SET/-)
AND
i_can_VehicleSpeed > = p_tng_kph_acc_vmin_regulation


THEN
o_can_adas_longi_state_comfort  shall switch to ""3"":""ALSCT_INREGULATION""
AND
o_sdvipc_setspeed shall be set to i_can_VehicleSpeed

Note :   default value for p_tng_kph_acc_vmin_regulation  to consider for  automatic gearbox is 0 "
"""

In [ ]:
inputs = tokenizer(
[
    tokenizer.bos_token + alpaca_prompt.format(
        instruction,
        test_REQ,
        "", # leave output blank for generation
    )
], return_tensors="pt").to("cuda")

In [ ]:
tokenizer.bos_token

'<s>'

In [ ]:
outputs = model.generate(
    **inputs,
    max_new_tokens=2048,
    use_cache=True,
    do_sample = False,
    pad_token_id=tokenizer.eos_token_id
)

Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

In [ ]:
print(
    tokenizer.decode(
        outputs[0][inputs.input_ids.shape[-1]:],
        skip_special_tokens=True,
        cleanup_tokenization_spaces=True
    )
)

TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 15
AND
i_can_SetPlusSwitche == SET/+
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 15
AND
i_can_SetMinusSwitche == SET/-
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 15
AND
i_can_SetPlusSwitche == SET/+
THEN
o_sdvipc_setspeed == i_can_VehicleSpeed

TC_4:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 15
AND
i_can_SetMinusSwitche == SET/-
THEN
o_sdvipc_setspeed == i_can_VehicleSpeed

In [ ]:
validation_set

,reqs,tc
0,\nSignals under test:\no_sdvipc_AdasCarouselCo...,IF\ni_can_CarouselModeSwitch == 1(Pressed)\nTH...
1,\nSignals under test:\no_sdvipc_ADASCarouselMo...,TC_1:\nIF\ni_can_CarouselModeSwitch == 1(Press...
2,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\no_can_adas_longi_state_comfort == 2...
3,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\no_can_adas_longi_state_comfort == 4...
4,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\nACC_Status == SUSPENDED\nAND\no_can...
5,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\no_can_adas_longi_state_comfort == 2...
6,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\no_can_adas_longi_state_comfort == 2...
7,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\no_can_adas_longi_state_comfort == 2...
8,\nSignals under test:\no_can_adas_longi_state_...,TC_1:\nIF\no_can_adas_longi_state_comfort == 2...

In [ ]:
reqs = validation_set['reqs'].to_list()

In [ ]:
tcs =[]
for i in reqs:
  inputs = tokenizer(
[
    tokenizer.bos_token + alpaca_prompt.format(
        instruction,
        i,
        "", # leave output blank for generation
    )
], return_tensors="pt").to("cuda")
  outputs = model.generate(
    **inputs,
    max_new_tokens=2048,
    use_cache=True,
    do_sample = False,
    pad_token_id=tokenizer.eos_token_id
)
  tc =tokenizer.decode(
        outputs[0][inputs.input_ids.shape[-1]:],
        skip_special_tokens=True,
        cleanup_tokenization_spaces=True
    )
  tcs.append(tc)

Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
for i in tcs:
  print(i)
  print("_"*30)

TC_1:
IF
i_can_CarouselModeSwitch == 1(Pressed)
THEN
o_sdvipc_AdasCarouselContent == CF_ALL_FEATURE_OFF(1)

TC_2:
IF
i_can_CarouselModeSwitch == 1(Pressed)
THEN
o_sdvipc_AdasCarouselContent == CF_SPEED_LIMITER(2)

TC_3:
IF
i_can_CarouselModeSwitch == 1(Pressed)
THEN
o_sdvipc_AdasCarouselContent == CF_ADAPTIVE_CRUISE_CONTROL(4)
______________________________
TC_1:
IF
i_can_CarouselModeSwitch == 1(Pressed)
AND
ACC is available
THEN
o_sdvipc_ADASCarouselModeSelected == 1(CF_ALL_FEATURE_OFF)

TC_2:
IF
i_can_CarouselModeSwitch == 1(Pressed)
AND
ACC is available
THEN
o_sdvipc_ADASCarouselModeSelected == 4(CF_ADAPTIVE_CRUISE_CONTROL)

TC_3:
IF
i_can_CarouselModeSwitch == 1(Pressed)
AND
ACC is available
THEN
o_sdvipc_ADASCarouselModeSelected == 2(CF_SPEED_LIMITER)
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_4:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_5:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_6:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_7:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_8:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_can_adas_longi_state_comfort == OFF

TC_9:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_10:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_11:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_12:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_13:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_14:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_15:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_16:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_17:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_18:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_19:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_20:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_21:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_22:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_23:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_TCS_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_24:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_AYC_Deactivated == Deactivated
THEN
o_sdvipc_AdasCarouselContent == OFF
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALCSCT_STOP(4)
AND
i_can_StandStillStatus == ACTIVATED
AND
Global_PWTWheelTorqueRequest < 6400Nm
THEN
o_can_adas_longi_state_comfort == ACC_Status(OFF)

TC_2:
IF
o_can_adas_longi_state_comfort == ALCSCT_STOP(4)
AND
i_can_StandStillStatus == ACTIVATED
AND
Global_PWTWheelTorqueRequest < 6400Nm
THEN
o_can_GlobalStandstillRequest == NO_REQUEST
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 35
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 35
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 40
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_4:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 40
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_5:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 45
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_6:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 45
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_7:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 50
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_8:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 50
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_9:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 55
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_10:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 55
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_11:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 60
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_12:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 60
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_13:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 65
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_14:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 65
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_15:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 70
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_16:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 70
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_17:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 75
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_18:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 75
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_19:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 80
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)

TC_20:
IF
o_can_adas_longi_state_comfort == ALSC_SUSPENDED(2)
AND
i_can_VehicleSpeed >= 80
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30(p_tng_kph_accoff_to_acc_speed_th_low)
AND
i_can_SetPlusSwitche == SET/+
THEN
o_can_adas_longi_state_comfort == ALSCT_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30(p_tng_kph_accoff_to_acc_speed_th_low)
AND
i_can_SetMinusSwitche == SET/-
THEN
o_can_adas_longi_state_comfort == ALSCT_INREGULATION(3)

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30(p_tng_kph_accoff_to_acc_speed_th_low)
AND
i_can_VehicleSpeed == 40(V_req_mps_SetSpeed)
THEN
o_sdvipc_setspeed == 40(V_req_mps_SetSpeed)
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_kph_accoff_to_acc_speed_th_low
AND
i_can_VehicleSpeed <= p_tng_kph_acc_to_accoff_speed_thd_high
AND
i_can_SetPlusSwitche == SET_PLUS
THEN
o_can_adas_longi_state_comfort == ALSTCT_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_kph_accoff_to_acc_speed_th_low
AND
i_can_VehicleSpeed <= p_tng_kph_acc_to_accoff_speed_thd_high
AND
i_can_SetMinusSwitche == SET_MINUS
THEN
o_can_adas_longi_state_comfort == ALSTCT_INREGULATION(3)

TC_3:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < p_tng_kph_acc_vmin_regulation
AND
i_can_SetPlusSwitche == SET_PLUS
THEN
o_sdvipc_setspeed == p_tng_kph_acc_vmin_regulation

TC_4:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < p_tng_kph_acc_vmin_regulation
AND
i_can_SetMinusSwitche == SET_MINUS
THEN
o_sdvipc_setspeed == p_tng_kph_acc_vmin_regulation
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30
AND
i_can_VehicleSpeed <= 180
AND
i_can_AdaptSpeedSwitch == 1
AND
TSR_OSP_SpeedLimit >= 30
THEN
o_can_adas_longi_state_comfort == INREGULATION

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30
AND
i_can_VehicleSpeed <= 180
AND
i_can_AdaptSpeedSwitch == 1
AND
TSR_OSP_SpeedLimit >= 30
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit
______________________________
TC_1:
IF
o_can_adas_longi_state_comfort == ALCSCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 0.7
AND
i_can_PlayPauseSwitch == 1
AND
i_can_PressedByDriver == 0
THEN
o_can_adas_longi_state_comfort == INREGULATION

TC_2:
IF
o_can_adas_longi_state_comfort == ALCSCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 0.7
AND
i_can_PlayPauseSwitch == 1
AND
i_can_PressedByDriver == 0
THEN
o_sdvipc_setspeed == V_req_mps_SetSpeed
______________________________

In [ ]:
# generated with do not assume condition added
test_req =""""
Signals under test:
o_can_adas_longi_state_comfort, o_sdvipc_setspeed, AutoRestart_Status

Involved input signals:
o_can_adas_longi_state_comfort , i_can_VehicleSpeed, i_can_gearLeverRequested, TSR_OSP_SpeedLimit, i_can_AdaptSpeedSwitch, i_can_PressedByDriver

Involved input parameters:
p_tng_kph_acc_vmin_activation_on_brake, p_tng_acc_min_regulation_speed

Requirement:
6.3.2-9 WHEN
o_can_adas_longi_state_comfort has value = ""2"":""ALSCT_NOREQUEST_STANDBY""  (ACC_status : SUSPENDED OR WAITING)
AND
i_can_VehicleSpeed < p_tng_kph_acc_vmin_activation_on_brake (default = 0.7 kph, tunable)
AND
i_can_gearLeverRequested is in Drive or Brake mode
AND
TSR_OSP_SpeedLimit ≥ p_tng_acc_min_regulation_speed (30 kph default, tunable)

IF i_can_AdaptSpeedSwitch is ""pressed""
AND
i_can_PressedByDriver = Brake Pedal Not Pressed

THEN
o_can_adas_longi_state_comfort shall switch to INREGULATION
AND
o_sdvipc_setspeed shall be set to :TSR_OSP_SpeedLimit value

ELSEIF i_can_ContextSwitch is ""pressed""
AND
i_can_PressedByDriver = Brake Pedal Pressed

THEN
o_can_adas_longi_state_comfort shall switch to INSTOP
AND
A-CC-SL system shall set AutoRestart_Status to Manual Restart
AND
o_sdvipc_setspeed shall be set to :TSR_OSP_SpeedLimit value

Note:  AutorestartStatus (obs::accAutorestartStatus) is not accessible at PCU boundaries. However, the conditions and the CarMaker scenario used to set this signal from PCU boundaries are detailed in ""ACC_SyRS_1274"".
"""

In [ ]:
inputs = tokenizer(
[
    tokenizer.bos_token + alpaca_prompt.format(
        instruction,
        test_req,
        "", # leave output blank for generation
    )
], return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=2048,
    use_cache=True,
    do_sample = False,
    pad_token_id=tokenizer.eos_token_id
)
tc =tokenizer.decode(
        outputs[0][inputs.input_ids.shape[-1]:],
        skip_special_tokens=True,
        cleanup_tokenization_spaces=True
    )

Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

In [ ]:
print(tc)

TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_can_adas_longi_state_comfort == INREGULATION

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
AutoRestart_Status == MANUAL_RESTART

TC_4:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_5:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_can_adas_longi_state_comfort == INSTOP

TC_6:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_7:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
AutoRestart_Status == MANUAL_RESTART

TC_8:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_can_adas_longi_state_comfort == INSTOP

TC_9:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_10:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_can_adas_longi_state_comfort == INSTOP

TC_11:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_12:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_can_adas_longi_state_comfort == INSTOP

TC_13:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_14:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_can_adas_longi_state_comfort == INSTOP

TC_15:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >= 30
AND
i_can_AdaptSpeedSwitch == PRESSED
AND
i_can_PressedByDriver == NOT_PRESSED
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit

TC_16:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 7
AND
i_can_gearLeverRequested == DRIVE
AND
TSR_OSP_SpeedLimit >=

In [ ]:
instruction = """You are a QA Engineer. Your task is to develop test cases based on the given requirements.
NO PROSE: Do not provide explanations, assumptions, or "Additional Information" sections.
STRICT CONSTRAINTS: 1.For every signal listed under "Signals under test", you must generate at least one dedicated test case.
Example: If there are 3 signals under test, you must generate at least 3 test cases (TC_1, TC_2, TC_3) to ensure full coverage.
2. To generate the test cases you can only use:
  - signals under test (Example: i_can_DriveModeSelector)
  - Involved input signals (Example: i_can_DriveModeSelector)
  - Involved input parameters (Example: p_tng_lka_min_speed_activation)
  - The following keywords: "IF", "AND", "OR", "THEN"
  - The following operators: "==", "!=", "<", ">", "<=", ">=
3. DO NOT assume any values. Only use whatever is given in the Input"""

In [ ]:
tcs =[]
for i in reqs:
  inputs = tokenizer(
[
    tokenizer.bos_token + alpaca_prompt.format(
        instruction,
        i,
        "", # leave output blank for generation
    )
], return_tensors="pt").to("cuda")
  outputs = model.generate(
    **inputs,
    max_new_tokens=2048,
    use_cache=True,
    pad_token_id=tokenizer.eos_token_id
)
  tc =tokenizer.decode(
        outputs[0][inputs.input_ids.shape[-1]:],
        skip_special_tokens=True,
        cleanup_tokenization_spaces=True
    )
  tcs.append(tc)

Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=2048) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
a = 1
for i in tcs:
  print(a)
  print(i)
  print("_"*30)
  a = a+1

1
TC_1:
IF
i_can_CarouselModeSwitch == 1(Pressed)
THEN
o_sdvipc_AdasCarouselContent == CF_ALL_FEATURE_OFF(1)

TC_2:
IF
i_can_CarouselModeSwitch == 1(Pressed)
THEN
o_sdvipc_AdasCarouselContent == CF_SPEED_LIMITER(2)

TC_3:
IF
i_can_CarouselModeSwitch == 1(Pressed)
THEN
o_sdvipc_AdasCarouselContent == CF_ADAPTIVE_CRUISE_CONTROL(4)
______________________________
2
TC_1:
IF
i_can_CarouselModeSwitch == 1(Pressed)
AND
o_sdvipc_ADASCarouselModeSelected == 1(CF_ALL_FEATURE_OFF)
THEN
o_sdvipc_ADASCarouselModeSelected == 4(CF_ADAPTIVE_CRUISE_CONTROL)

TC_2:
IF
i_can_CarouselModeSwitch == 1(Pressed)
AND
o_sdvipc_ADASCarouselModeSelected == 4(CF_ADAPTIVE_CRUISE_CONTROL)
THEN
o_sdvipc_ADASCarouselModeSelected == 2(CF_SPEED_LIMITER)
______________________________
3
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_4:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_5:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_6:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_7:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_8:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_can_adas_longi_state_comfort == OFF

TC_9:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_10:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_11:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_12:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_13:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_14:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_15:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_16:
IF
o_can_adas_longi_state_comfort == ALSC_INREGULATION(3)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_17:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_18:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_19:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_20:
IF
o_can_adas_longi_state_comfort == ALSC_STOP(4)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_21:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_22:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_TCS_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF

TC_23:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_ADASCarouselModeSelected == OFF

TC_24:
IF
o_can_adas_longi_state_comfort == ALSC_OVERRIDE(5)
AND
i_can_i_can_AYC_Deactivated == DEACTIVATED
THEN
o_sdvipc_AdasCarouselContent == OFF
______________________________
4
TC_1:
IF
o_can_adas_longi_state_comfort == ALCSCT_STOP(4)
AND
i_can_StandStillStatus == ACTIVATED
AND
Global_PWTWheelTorqueRequest < 6400Nm
THEN
o_can_adas_longi_state_comfort == ACC_Status(OFF)

TC_2:
IF
o_can_adas_longi_state_comfort == ALCSCT_STOP(4)
AND
i_can_StandStillStatus == ACTIVATED
AND
Global_PWTWheelTorqueRequest < 6400Nm
THEN
o_can_GlobalStandstillRequest == NO_REQUEST
______________________________
5
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 35
AND
i_can_CarouselModeSwitch == 1
THEN
o_can_adas_longi_state_comfort == ALSCT_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 35
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 50

TC_3:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 40
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 55

TC_4:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 45
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 60

TC_5:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 50
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 65

TC_6:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 55
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 70

TC_7:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 60
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 75

TC_8:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 65
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 80

TC_9:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 70
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 85

TC_10:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 75
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 90

TC_11:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 80
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 95

TC_12:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 85
AND
i_can_CarouselModeSwitch == 1
THEN
o_sdvipc_setspeed == 100
______________________________
6
TC_1:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30(p_tng_kph_accoff_to_acc_speed_th_low)
AND
i_can_SetPlusSwitche == SET/+
THEN
o_can_adas_longi_state_comfort == ALSTCT_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30(p_tng_kph_accoff_to_acc_speed_th_low)
AND
i_can_SetMinusSwitche == SET/-
THEN
o_can_adas_longi_state_comfort == ALSTCT_INREGULATION(3)

TC_3:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= 30(p_tng_kph_accoff_to_acc_speed_th_low)
AND
i_can_VehicleSpeed == 40(V_req_mps_SetSpeed)
THEN
o_sdvipc_setspeed == 40(V_req_mps_SetSpeed)
______________________________
7
TC_1:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_kph_accoff_to_acc_speed_th_low
AND
i_can_VehicleSpeed <= p_tng_kph_acc_to_accoff_speed_thd_high
AND
i_can_SetPlusSwitche == SET/+
AND
i_can_VehicleSpeed < p_tng_kph_acc_vmin_regulation
THEN
o_can_adas_longi_state_comfort == ALSTCT_INREGULATION(3)

TC_2:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_kph_accoff_to_acc_speed_th_low
AND
i_can_VehicleSpeed <= p_tng_kph_acc_to_accoff_speed_thd_high
AND
i_can_SetMinusSwitche == SET/-
AND
i_can_VehicleSpeed < p_tng_kph_acc_vmin_regulation
THEN
o_can_adas_longi_state_comfort == ALSTCT_INREGULATION(3)

TC_3:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_kph_accoff_to_acc_speed_th_low
AND
i_can_VehicleSpeed <= p_tng_kph_acc_to_accoff_speed_thd_high
AND
i_can_SetPlusSwitche == SET/+
THEN
o_sdvipc_setspeed == p_tng_kph_acc_vmin_regulation

TC_4:
IF
o_can_adas_longi_state_comfort == ALSTCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_kph_accoff_to_acc_speed_th_low
AND
i_can_VehicleSpeed <= p_tng_kph_acc_to_accoff_speed_thd_high
AND
i_can_SetMinusSwitche == SET/-
THEN
o_sdvipc_setspeed == p_tng_kph_acc_vmin_regulation
______________________________
8
TC_1:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_acc_min_regulation_speed
AND
i_can_AdaptSpeedSwitch == 1
AND
TSR_OSP_SpeedLimit >= p_tng_acc_min_regulation_speed
THEN
o_can_adas_longi_state_comfort == INREGULATION

TC_2:
IF
o_can_adas_longi_state_comfort == ALSC_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed >= p_tng_acc_min_regulation_speed
AND
i_can_AdaptSpeedSwitch == 1
AND
TSR_OSP_SpeedLimit >= p_tng_acc_min_regulation_speed
THEN
o_sdvipc_setspeed == TSR_OSP_SpeedLimit
______________________________
9

TC_1:
IF
o_can_adas_longi_state_comfort == ALCSCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 0.7
AND
i_can_PlayPauseSwitch == 1
AND
i_can_PressedByDriver == 0
THEN
o_can_adas_longi_state_comfort == INREGULATION

TC_2:
IF
o_can_adas_longi_state_comfort == ALCSCT_NOREQUEST_STANDBY(2)
AND
i_can_VehicleSpeed < 0.7
AND
i_can_PlayPauseSwitch == 1
AND
i_can_PressedByDriver == 0
THEN
o_sdvipc_setspeed == V_req_mps_SetSpeed
______________________________